### ISSUE TITLE
Use requirements from invenio-integration-tests

### ISSUE THREAD

**Issue by mirekys** [oarepo/oarepo#12]
When the new requirements are tested and published by the [invenio-integration-tests](https://github.com/oarepo/invenio-integration-tests) module, we should:

- [x] fetch tested requirements for Invenio 3.2 from `invenio-integration-tests`
- [x] load requirements into `oarepo` package's `setup.py`
- [x] build new oarepo package using those requirements, tag the version using scheme: ${INVENIO_VERSION}.${OAREPO_VERSION}, _(e.g. 3.2.1.3 for Invenio 3.2.1)_
- [x] publish the new package version to PyPi

To detect, if there is some change in the requirements in the invenio-integration-tests repo, and to trigger the build, we should have a look on Github Actions. As an alternative, we may use some weekly Travis cron job

**Comment by milkydan** [comment]
Current update - necessity to modify micro-api to use requirements from oarepo
- test of micro-api should be: started rest-api, publish record, search record and download record

**Comment by thlava-cesnet** [comment]
rest-api testing done in [invenio-integration-tests](https://github.com/oarepo/invenio-integration-tests)

**Comment by mirekys** [comment]
Thanks for the tests @thlava-cesnet, we still need to update `oarepo-micro-api` to have autocreated branches using versions of `oarepo` branches (currently just the 3.3.0)

**Comment by mirekys** [comment]
UPDATE: `oarepo-micro-api` now uses tested oarepo builds
