### ISSUE TITLE
Handle.net integration

### ISSUE THREAD

**Issue by mirekys** [oarepo/oarepo#32]
Research on how to integrate with Handle.net APIs to register Handle.net identifiers for Invenio records.

**Comment by milkydan** [comment]
Ahoj, zacal jsem tim, ze jsem zkousel prohledat cely invenio repozitar a pogooglit po integraci handlu a bohuzel to vypada ze nic takoveho neexistuje, nasel jsem jen info k DOI
https://invenio-pidstore.readthedocs.io/en/latest/usage.html

**Comment by milkydan** [comment]
Zkusim se tedy podivat trosku bliz na handle a jeho API, jestli by to neslo jednoduse pouzit jako PID generator namisto DOI v inveniu

**Comment by mirekys** [comment]
> Zkusim se tedy podivat trosku bliz na handle a jeho API, jestli by to neslo jednoduse pouzit jako PID generator namisto DOI v inveniu

Dikes, podivej prosim v prvnim priblizeni, jestli neexistuje nejaky pouzitelny pythoni klient, co by umel zaregistrovat handle pres to jejich API

**Comment by mirekys** [comment]
Handle nebudeme resit, mame DOI
